package(default_visibility = ["//visibility:public"])

cc_library(
	name = "simple_pizza_factory",
	srcs = [
		"simple_pizza_factory.h",
	],
	deps = [
		"//common/pizza:cheese_pizza",
		"//common/pizza:veggie_pizza",
	],
)