package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
	name = "waitress",
	srcs = [
		"waitress.h",
		"waitress.cc",
	],
	deps = [
		"//menu_component:menu_component_interface",
	],
)