package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
	name = "home_theather_facade_test",
	srcs = [
		"home_theather_facade_test.cc",
	],
	copts = [],
	deps = [
		"//material:home_theather_facade",
		"//material:normal_amp",
		"//material:normal_dvd",
		"//material:normal_screen",
	],
)