package(default_visibility = ["//visibility:public"])

cc_binary(
	name = "duck_drive_test",
	copts = [
		"-O2",
		"-Wall",
	],
	srcs = [
		"duck_drive_test.cc",
	],
	deps = [
	       "//tools:turkey_adapter",
	       "//tools:wild_turkey",
	],
)