package(default_visibility = ["//visibility:public"])

cc_library(
   name = "quack-behavior-lib",
   copts = [
      "-std=c++17",
      "-O2",
      "-Wall"
   ],
   srcs = glob([
	 "mute_quack.cc",
	 "quack.cc",
    "squeak.cc",
    "mute_quack.h",
    "quack.h",
    "squeak.h",
    "quack_behavior.h",
   ]),	
)