package(default_visibility = ["//visibility:public"])

cc_library(
   name = "quack-behavior-lib",
   copts = [
      "-std=c++17",
      "-O2",
      "-Wall"
   ],
   includes = ["quack-behavior"],
   srcs = glob([
	 "quack-behavior/*.cc",
	 "quack-behavior/*.h",
   ]),	
)