package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "template_method_pattern_test",
  srcs = [
        "template_method_pattern_test.cc",
  ],
  copts = [],
  deps = [
       "//coffee_and_tea:coffee_with_hook",
       "//coffee_and_tea:tea_with_hook",
  ],
)