package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
	name = "caffeine_beverage_with_hook_interface",
	srcs = [
		"caffeine_beverage_with_hook.h",
		"caffeine_beverage_with_hook.cc"
	],
)